WITH previous_project_names(id, name) AS (
  VALUES
    ('cmo-cus-0001-cu-space-development-unplanned-major', 'Space Development Unplanned Major'),
    ('com-chc-0008-ch-002-ogden-playground-renewal', 'Ogden Playground Renewal'),
    ('com-chc-0008-ch-002-woodcrest', 'Woodcrest'),
    ('com-fac-0004-fa-001-diagrams-net-zero-integration', 'Diagrams Net-Zero Integration'),
    ('com-fac-0004-fa-002-component-repair-office-renovations', 'Component Repair Office Renovations'),
    ('com-fac-0004-fa-004-assessments', 'Assessments'),
    ('com-fac-0004-fa-006-aquatics-capital-program', 'Aquatics Capital Program'),
    ('com-fac-0004-fa-007-arenas-capital-program-outdoor-pool', 'Arenas Capital Program Outdoor Pool'),
    ('com-flt-0007-fl-001-diversion-fleet-renewal', 'Diversion Fleet Renewal'),
    ('com-hom-0022-pj-001-reconfiguration-facility-cyclical', 'Reconfiguration Facility Cyclical'),
    ('com-hom-0022-pj-002-replacements-jasper-furnishings-and', 'Replacements Jasper Furnishings and'),
    ('com-hom-0022-pj-003-replacements-building-condition', 'Replacements Building Condition'),
    ('com-hom-0022-pj-004-equipment-food-services-cyclical', 'Equipment Food Services Cyclical'),
    ('com-hom-0022-pj-007-replacements-residential-furnishings', 'Replacements Residential Furnishings'),
    ('com-hom-0022-pj-008-and-equipment', 'and Equipment'),
    ('com-rec-0032-dd-007-plan', 'Plan'),
    ('com-rec-0034-ei-002-renewal', 'Renewal'),
    ('com-rec-0034-ei-004-equipment', 'Equipment'),
    ('com-rec-0034-ei-008-and-minor-projects', 'and Minor Projects'),
    ('com-rec-0034-ei-018-stage-equipment-arena-and-stadia', 'Stage Equipment Arena and Stadia'),
    ('com-rec-0034-ei-020-equipment-renewal', 'Equipment Renewal'),
    ('com-trn-0002-ct-001-shelter-replacement-accessible-stop', 'Shelter Replacement Accessible Stop'),
    ('com-trn-0002-ct-002-improvements', 'Improvements'),
    ('com-trn-0009-ct-001-transit-rebranding-transit-on-demand', 'Transit Rebranding Transit On-Demand'),
    ('com-trn-0009-ct-004-vehicles', 'Vehicles'),
    ('gro-com-0001-cc-001-communications-asset-maintenance-and', 'Communications Asset Maintenance and'),
    ('gro-gmo-0001-ad-replacement', 'Replacement'),
    ('ior-san-0002-ni-001-technology', 'Technology'),
    ('ior-san-0002-ni-002-small-equipment-wastewater-innovations', 'Small Equipment Wastewater Innovations'),
    ('ior-san-0002-ni-003-program-efficiency', 'Program Efficiency'),
    ('ior-san-0002-ni-009-infrastructure-advanced-metering', 'Infrastructure Advanced Metering'),
    ('ior-san-0003-fr-002-equipment-replacement-1-046-0-1-046-0', 'Equipment Replacement 1,046.0 1,046.0'),
    ('ior-san-0004-sa-003-unspecified-maintenance-hole', 'Unspecified Maintenance Hole'),
    ('ior-san-0004-sa-005-appurtenance-rehabilitation-sanitary-sewer-replacement', 'Appurtenance Rehabilitation Sanitary Sewer Replacement'),
    ('ior-san-0004-sa-006-house-lateral-lining-sanitary-sewer-cleaning', 'House Lateral Lining Sanitary Sewer Cleaning'),
    ('ior-san-0004-sa-018-memorial-ave-queen-to-inchiquin', 'Memorial Ave - Queen to Inchiquin'),
    ('ior-san-0004-sa-019-replacement', 'Replacement'),
    ('ior-san-0004-sa-020-replacement', 'Replacement'),
    ('ior-san-0004-sa-045-and-inspection', 'and Inspection'),
    ('ior-san-0004-sa-065-requirement', 'Requirement'),
    ('ior-san-0004-sa-076-replacement', 'Replacement'),
    ('ior-san-0004-sa-086-replacement', 'Replacement'),
    ('ior-san-0004-sa-089-replacement', 'Replacement'),
    ('ior-san-0004-sa-090-replacement', 'Replacement'),
    ('ior-san-0004-sa-091-replacement', 'Replacement'),
    ('ior-san-0005-wp-002-wpcp-electrical-wpcp-building-and', 'WPCP Electrical WPCP Building and'),
    ('ior-san-0005-wp-003-grounds', 'Grounds'),
    ('ior-san-0005-wp-005-wpcp-hvac-sewage-pumping', 'WPCP HVAC Sewage Pumping'),
    ('ior-san-0005-wp-006-stations', 'Stations'),
    ('ior-san-0005-wp-007-wpcp-professional-fees-wpcp-unplanned', 'WPCP Professional Fees WPCP Unplanned'),
    ('ior-san-0005-wp-008-repairs-wpcp-generator', 'Repairs WPCP Generator'),
    ('ior-san-0005-wp-009-standby-power', 'Standby Power'),
    ('ior-san-0007-ps-001-and-contract-admin-professional-fees-for', 'and Contract Admin Professional Fees for'),
    ('ior-san-0007-ps-002-studies', 'Studies'),
    ('ior-sow-0001-ls-001-process-improvements-infrastructure', 'Process Improvements Infrastructure'),
    ('ior-sow-0001-ls-002-improvements', 'Improvements'),
    ('ior-sow-0001-ls-019-monitoring-study', 'Monitoring Study'),
    ('ior-waw-0001-tp-002-wtp-electrical-wtp-buildings-and', 'WTP Electrical WTP Buildings and'),
    ('ior-waw-0001-tp-004-wtp-instrumentation-pump-station-reservoir', 'WTP Instrumentation Pump Station / Reservoir'),
    ('ior-waw-0001-tp-005-grounds-pump-station-reservoir', 'Grounds Pump Station / Reservoir'),
    ('ior-waw-0001-tp-006-process-pump-station-reservoir', 'Process Pump Station / Reservoir'),
    ('ior-waw-0001-tp-007-electrical-pump-station-reservoir', 'Electrical Pump Station / Reservoir'),
    ('ior-waw-0001-tp-009-instrumentation', 'Instrumentation'),
    ('ior-waw-0001-tp-010-buildings-and-grounds', 'Buildings and Grounds'),
    ('ior-waw-0002-ni-001-equipment-water-use-innovation', 'Equipment Water Use Innovation'),
    ('ior-waw-0002-ni-0014-infrastructure', 'Infrastructure'),
    ('ior-waw-0002-ni-002-program-efficiency-large-water-meter', 'Program Efficiency Large Water Meter'),
    ('ior-waw-0002-ni-004-replacement-program', 'Replacement Program'),
    ('ior-waw-0003-fw-001-equipment-replacement', 'Equipment Replacement'),
    ('ior-waw-0004-wr-002-unspecified-replacement-s-watermain-replacement', 'Unspecified Replacement s Watermain Replacement'),
    ('ior-waw-0004-wr-003-kerr-hydrant-replacement-lead-service', 'Kerr Hydrant Replacement Lead Service'),
    ('ior-waw-0004-wr-004-and-flow-cleaning-and-cement', 'and Flow Cleaning and Cement'),
    ('ior-waw-0004-wr-013-replacement-program-looping-program-quality', 'Replacement Program Looping Program - Quality'),
    ('ior-waw-0004-wr-017-mortar-lining-looping-waterford', 'Mortar Lining Looping - Waterford'),
    ('ior-waw-0004-wr-067-sheep-ranch-rail-crossing-watermain-replacement', 'Sheep Ranch Rail Crossing Watermain Replacement'),
    ('ior-waw-0004-wr-124-phillips-phillips-to-mcauliff-watermain-replacement', 'Phillips - Phillips to McAuliff Watermain Replacement'),
    ('ior-waw-0004-wr-154-ambrose-street-watermain-replacement', 'Ambrose Street Watermain Replacement'),
    ('ior-waw-0004-wr-155-lincoln-street-watermain-replacement', 'Lincoln Street Watermain Replacement'),
    ('ior-waw-0004-wr-156-manitou-street', 'Manitou Street'),
    ('ior-waw-0004-wr-158-expansion', 'Expansion'),
    ('ior-waw-0004-wr-161-to-carrick', 'to Carrick'),
    ('ior-waw-0004-wr-168-river-to-theresa', 'River to Theresa'),
    ('ior-waw-0005-ne-001-waterworks', 'Waterworks'),
    ('ior-waw-0006-pw-001-studies-dwqms-audit-pre-engineering-design', 'Studies, DWQMS, Audit Pre-Engineering Design'),
    ('iot-cfc-0001-cs-012-canada-games-complex-canada-games-complex', 'Canada Games Complex Canada Games Complex /'),
    ('iot-cfc-0001-cs-022-rehabilitation', 'Rehabilitation'),
    ('iot-cfc-0003-cs-001-whalen-building-customer-service-office', 'Whalen Building Customer Service Office'),
    ('iot-cfc-0005-cs-001-waste-facility', 'Waste Facility'),
    ('iot-cfc-0018-cs-001-audits-environmental', 'Audits Environmental'),
    ('iot-eng-0001-pf-001-reports-engineering-traffic', 'Reports Engineering Traffic'),
    ('iot-eng-0001-pf-002-studies', 'Studies'),
    ('iot-eng-0001-pf-005-active-transportation-environmental', 'Active Transportation Environmental'),
    ('iot-eng-0001-pf-007-acquisitions', 'Acquisitions'),
    ('iot-eng-0001-pf-017-assessments', 'Assessments'),
    ('iot-eng-0001-pf-026-stormwater-cli-eca-asphalt-pavement', 'Stormwater CLI ECA Asphalt - Pavement'),
    ('iot-env-0001-st-001-trunk-ditching-rural-roads-rehabilitation-replacement', 'Trunk Ditching Rural Roads Rehabilitation/Replacement'),
    ('iot-env-0001-st-002-unspecified', 'Unspecified'),
    ('iot-env-0001-st-003-storm-sewer-inspections-residential-drainage', 'Storm Sewer Inspections Residential Drainage'),
    ('iot-env-0001-st-017-assistance-program', 'Assistance Program'),
    ('iot-env-0001-st-022-intercity-priorities-low-impact-development', 'Intercity Priorities Low Impact Development'),
    ('iot-env-0001-st-039-facilities-rural-drainage', 'Facilities Rural Drainage'),
    ('iot-env-0001-st-091-improvement-urban-drainage', 'Improvement Urban Drainage'),
    ('iot-env-0001-st-092-improvements', 'Improvements'),
    ('iot-env-0001-st-097-management', 'Management'),
    ('iot-env-0001-st-105-management-watermain-network', 'Management Watermain Network'),
    ('iot-fir-0040-fr-001-equipment-fire-hose-nozzles-and', 'Equipment Fire Hose, Nozzles and'),
    ('iot-fir-0040-fr-002-appliances-aoda-station', 'Appliances AODA Station'),
    ('iot-fir-0040-fr-005-improvements', 'Improvements'),
    ('iot-pks-0001-gp-029-waverley-park-renewal-recreation-trail', 'Waverley Park Renewal Recreation Trail'),
    ('iot-pks-0001-gp-030-urban-canopy-projects-urban-forest', 'Urban Canopy Projects Urban Forest'),
    ('iot-pks-0002-as-002-baseball-diamonds-tennis-and-pickleball', 'Baseball Diamonds Tennis and Pickleball'),
    ('iot-pks-0002-as-003-courts-soccer-and-cricket', 'Courts Soccer and Cricket'),
    ('iot-pks-0002-as-004-fields-bleacher-seat-and-bench', 'Fields Bleacher Seat and Bench'),
    ('iot-pks-0002-as-005-replacement', 'Replacement'),
    ('iot-pks-0003-rt-001-reconstruction-festival-area-renewal', 'Reconstruction Festival Area Renewal'),
    ('iot-pks-0003-rt-007-trails-public-art-maintenance', 'Trails Public Art Maintenance'),
    ('iot-pks-0005-uf-001-stewardship', 'Stewardship'),
    ('iot-pks-0006-go-001-golf-course-equipment-golf-course-grounds', 'Golf Course Equipment Golf Course Grounds'),
    ('iot-pks-0006-go-002-rehabilitation-program', 'Rehabilitation Program'),
    ('iot-rds-0001-br-008-inspection-william-street-bridge', 'Inspection William Street Bridge'),
    ('iot-rds-0001-br-011-program-structural-culvert', 'Program Structural Culvert'),
    ('iot-rds-0001-br-034-culvert-headwall-watermain-replacement', 'Culvert Headwall Watermain Replacement'),
    ('iot-rds-0001-br-036-design-harbour-exp-trail-bridge', 'Design Harbour Exp Trail Bridge'),
    ('iot-rds-0001-br-039-replacement-pacific-avenue-bridge', 'Replacement Pacific Avenue Bridge'),
    ('iot-rds-0001-br-040-reconstruction-harbour-exp-trail-girder', 'Reconstruction Harbour Exp Trail Girder'),
    ('iot-rds-0001-br-041-over-mcintyre-design-mckellar-island-to', 'Over McIntyre Design McKellar Island to'),
    ('iot-rds-0001-br-042-bridge-lyon-s-channel-oliver-rd-over-mcintyre', 'Bridge @ Lyon''s Channel Oliver Rd Over McIntyre'),
    ('iot-rds-0001-br-044-river-pedestrian-bridge-central-ave-overpass', 'River Pedestrian Bridge Central Ave Overpass'),
    ('iot-rds-0001-br-047-railing-replacement', 'Railing Replacement'),
    ('iot-rds-0003-ar-001-patching-railway-crossing', 'Patching Railway Crossing'),
    ('iot-rds-0003-ar-006-sealing-asphalt-miscellaneous', 'Sealing Asphalt - Miscellaneous'),
    ('iot-rds-0003-ar-007-management-asphalt-enhanced', 'Management Asphalt - Enhanced'),
    ('iot-rds-0003-ar-008-improvements-rural-roads-granular', 'Improvements Rural Roads Granular'),
    ('iot-rds-0003-ar-044-pavement-management', 'Pavement Management'),
    ('iot-rds-0003-ar-160-memorial-2-to-ontario-nd-hawkridge-falconcrest', 'Memorial - 2 to Ontario nd Hawkridge - Falconcrest'),
    ('iot-rds-0003-ar-175-to-southcliff-john-st-rd-community', 'to Southcliff John St Rd - Community'),
    ('iot-rds-0003-ar-185-hall-to-lawrence-john-st-rd-lawrence-to', 'Hall to Lawrence John St Rd - Lawrence to'),
    ('iot-rds-0003-ar-189-reconstruction', 'Reconstruction'),
    ('iot-rds-0003-ar-193-reconstruction-street-lighting', 'Reconstruction Street Lighting'),
    ('iot-rds-0003-ar-196-river-to-crescent', 'River to Crescent'),
    ('iot-rds-0003-ar-197-mapleward', 'Mapleward'),
    ('iot-rds-0003-ar-218-reconstruction-street-lighting', 'Reconstruction Street Lighting'),
    ('iot-rds-0003-ar-220-reconstruction-stormwater', 'Reconstruction Stormwater'),
    ('iot-rds-0003-ar-221-reconstruction-sanitary-sewer', 'Reconstruction Sanitary Sewer'),
    ('iot-rds-0003-ar-222-reconstruction-sanitary-sewer', 'Reconstruction Sanitary Sewer'),
    ('iot-rds-0003-ar-223-reconstruction-street-lighting', 'Reconstruction Street Lighting'),
    ('iot-rds-0003-ar-226-reconstruction-sanitary-sewer', 'Reconstruction Sanitary Sewer'),
    ('iot-rds-0003-ar-228-reconstruction-sanitary-sewer', 'Reconstruction Sanitary Sewer'),
    ('iot-rds-0004-rn-024-nw-arterial-design-nw-arterial-property', 'NW Arterial Design NW Arterial Property'),
    ('iot-rds-0004-rn-028-improvements', 'Improvements'),
    ('iot-rds-0004-rn-030-improvement-traffic-signals-burwood', 'Improvement Traffic Signals - Burwood'),
    ('iot-rds-0005-ru-001-upgrades', 'Upgrades'),
    ('iot-rds-0006-sr-003-alternatives', 'Alternatives'),
    ('iot-rds-0006-sr-077-sidewalk-replacement-sanitary-sewer', 'Sidewalk Replacement Sanitary Sewer'),
    ('iot-rds-0006-sr-099-sidewalk-replacement-sanitary-sewer', 'Sidewalk Replacement Sanitary Sewer'),
    ('iot-rds-0007-ts-001-program', 'Program'),
    ('iot-rds-0007-ts-002-detection-program-audible-pedestrian', 'Detection Program Audible Pedestrian'),
    ('iot-rds-0007-ts-003-signals-signal-upgrading', 'Signals Signal Upgrading'),
    ('iot-rds-0007-ts-005-program', 'Program'),
    ('iot-rds-0007-ts-014-pedestrian-crossovers-intersection-partial', 'Pedestrian Crossovers Intersection Partial'),
    ('iot-rds-0007-ts-016-rebuilds', 'Rebuilds'),
    ('iot-rds-0007-ts-037-rd-oliver-rd', 'Rd @ Oliver Rd'),
    ('iot-rds-0008-sn-002-sidewalks-unspecified-cameron-st-bus-stop-to', 'Sidewalks (Unspecified) Cameron St - Bus Stop to'),
    ('iot-rds-0008-sn-048-minnesota-to-mckenzie-new-sidewalk', 'Minnesota to McKenzie New Sidewalk'),
    ('iot-rds-0008-sn-049-vickers-st-n', 'Vickers St N'),
    ('iot-rds-0008-sn-053-prince-arthur-to-minnesota', 'Prince Arthur to Minnesota'),
    ('iot-rds-0010-sl-001-program-system-upgrading', 'Program System Upgrading'),
    ('iot-rds-0010-sl-002-program-pole-replacement', 'Program Pole Replacement'),
    ('iot-rds-0010-sl-004-program-underground-duct', 'Program Underground Duct'),
    ('iot-rds-0010-sl-031-replacement', 'Replacement'),
    ('iot-rds-0010-sl-069-brodie-miles-to-donald-victoria-archibald-to', 'Brodie - Miles to Donald Victoria - Archibald to'),
    ('iot-rds-0010-sl-070-mckellar', 'McKellar'),
    ('iot-rds-0010-sl-072-replacement', 'Replacement'),
    ('iot-rds-0010-sl-085-replacement-sanitary-sewer', 'Replacement Sanitary Sewer'),
    ('iot-rds-0010-sl-087-replacement', 'Replacement'),
    ('iot-sow-0003-sw-001-strategy-initiatives', 'Strategy Initiatives'),
    ('iot-sow-0003-sw-007-packer-solid-waste-and', 'Packer Solid Waste and'),
    ('iot-sow-0003-sw-009-facility-mapleward-solid', 'Facility Mapleward Solid'),
    ('osb-lib-0008-lb-renewal', 'Renewal'),
    ('osb-lib-0010-lb-and-repair-waverley-library-elevator', 'and Repair Waverley Library Elevator'),
    ('osb-lib-0011-lb-infrastructure', 'Infrastructure'),
    ('osb-lib-0012-lb-maintenance', 'Maintenance'),
    ('osb-pkg-0001-pk-parking-meters-waterfront-district', 'Parking Meters Waterfront District'),
    ('osb-pkg-0002-pk-parkade-repairs', 'Parkade Repairs'),
    ('osb-pol-0035-ps-maintenance', 'Maintenance'),
    ('osb-pol-0036-ps-replacement', 'Replacement')
)
UPDATE public.capital_projects p
SET name = n.name,
    official_name = n.name
FROM previous_project_names n
WHERE p.id = n.id;

DELETE FROM public.capital_project_approvals
WHERE approval_id = 'capital-budget-2026-2027-ior-waw-0004-wr-169-watermain-replacement';

DELETE FROM public.capital_projects
WHERE id = 'ior-waw-0004-wr-169-watermain-replacement';
