WITH official_project_names(id, name) AS (
VALUES
    ('iot-rds-0003-ar-214-pavement-resurfacing-golf-links-harbour', 'Pavement Resurfacing Golf Links @ Harbour'),
    ('iot-rds-0004-rn-031-expressway-lane-expansion', 'Expressway - Lane Expansion'),
    ('iot-rds-0008-sn-057-sidewalks', 'Sidewalks'),
    ('iot-rds-0007-ts-038-traffic-signals', 'Traffic Signals'),
    ('iot-env-0001-st-104-stormwater-pond', 'Stormwater Pond'),
    ('iot-rds-0004-rn-028-improvements', 'Improvements'),
    ('ior-san-0001-ne-009-sanitary-sewer', 'Sanitary Sewer'),
    ('ior-waw-0005-ne-004-watermain', 'Watermain'),
    ('iot-rds-0004-rn-030-improvement-traffic-signals-burwood', 'Improvement Traffic Signals - Burwood'),
    ('iot-rds-0007-ts-037-rd-oliver-rd', 'Rd @ Oliver Rd'),
    ('ior-san-0001-ne-008-phase-3-sanitary-sewer', 'Phase 3 - Sanitary Sewer'),
    ('ior-waw-0005-ne-003-phase-3-watermain', 'Phase 3 - Watermain'),
    ('iot-env-0001-st-105-management-watermain-network', 'Management Watermain Network'),
    ('ior-waw-0004-wr-158-expansion', 'Expansion'),
    ('ior-waw-0005-ne-001-waterworks', 'Waterworks'),
    ('ior-san-0001-ne-001-subdivision-oversizing-wastewater', 'Subdivision Oversizing - Wastewater'),
    ('iot-rds-0003-ar-198-surface-treatment', 'Surface Treatment'),
    ('iot-rds-0003-ar-189-reconstruction', 'Reconstruction'),
    ('iot-rds-0010-sl-074-streetlighting', 'Streetlighting'),
    ('iot-rds-0006-sr-077-sidewalk-replacement-sanitary-sewer', 'Sidewalk Replacement Sanitary Sewer'),
    ('ior-san-0004-sa-076-replacement', 'Replacement'),
    ('ior-waw-0004-wr-141-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-218-reconstruction-street-lighting', 'Reconstruction Street Lighting'),
    ('iot-rds-0010-sl-085-replacement-sanitary-sewer', 'Replacement Sanitary Sewer'),
    ('ior-san-0004-sa-089-replacement', 'Replacement'),
    ('iot-rds-0003-ar-228-reconstruction-sanitary-sewer', 'Reconstruction Sanitary Sewer'),
    ('ior-san-0004-sa-019-replacement', 'Replacement'),
    ('ior-waw-0004-wr-172-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-220-reconstruction-stormwater', 'Reconstruction Stormwater'),
    ('iot-env-0001-st-097-management', 'Management'),
    ('ior-waw-0004-wr-170-watermain-looping', 'Watermain Looping'),
    ('iot-rds-0010-sl-078-street-lighting-duct', 'Street Lighting (Duct)'),
    ('iot-rds-0006-sr-099-sidewalk-replacement-sanitary-sewer', 'Sidewalk Replacement Sanitary Sewer'),
    ('ior-san-0004-sa-086-replacement', 'Replacement'),
    ('ior-waw-0004-wr-027-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-196-river-to-crescent', 'River to Crescent'),
    ('iot-rds-0001-br-034-culvert-headwall-watermain-replacement', 'Culvert Headwall Watermain Replacement'),
    ('ior-waw-0004-wr-168-river-to-theresa', 'River to Theresa'),
    ('iot-rds-0008-sn-048-minnesota-to-mckenzie-new-sidewalk', 'Minnesota to McKenzie New Sidewalk'),
    ('iot-rds-0008-sn-053-prince-arthur-to-minnesota', 'Prince Arthur to Minnesota'),
    ('ior-waw-0004-wr-157-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-221-reconstruction-sanitary-sewer', 'Reconstruction Sanitary Sewer'),
    ('ior-san-0004-sa-090-replacement', 'Replacement'),
    ('ior-waw-0004-wr-171-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-222-reconstruction-sanitary-sewer', 'Reconstruction Sanitary Sewer'),
    ('ior-san-0004-sa-091-replacement', 'Replacement'),
    ('ior-waw-0004-wr-174-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-223-reconstruction-street-lighting', 'Reconstruction Street Lighting'),
    ('iot-rds-0010-sl-087-replacement', 'Replacement'),
    ('ior-waw-0004-wr-135-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-193-reconstruction-street-lighting', 'Reconstruction Street Lighting'),
    ('iot-rds-0010-sl-072-replacement', 'Replacement'),
    ('ior-waw-0004-wr-153-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-226-reconstruction-sanitary-sewer', 'Reconstruction Sanitary Sewer'),
    ('ior-san-0004-sa-020-replacement', 'Replacement'),
    ('ior-waw-0004-wr-088-watermain-replacement', 'Watermain Replacement'),
    ('iot-rds-0003-ar-006-sealing-asphalt-miscellaneous', 'Sealing Asphalt - Miscellaneous'),
    ('iot-rds-0003-ar-001-patching-railway-crossing', 'Patching Railway Crossing'),
    ('iot-rds-0003-ar-008-improvements-rural-roads-granular', 'Improvements Rural Roads Granular'),
    ('iot-rds-0005-ru-001-upgrades', 'Upgrades'),
    ('iot-rds-0003-ar-050-water-park-to-bay', 'Water - Park to Bay'),
    ('iot-rds-0003-ar-145-hot-in-place-recycling', 'Hot-in-Place Recycling'),
    ('iot-rds-0003-ar-158-mountdale-walsh-to-arthur', 'Mountdale-Walsh to Arthur'),
    ('iot-rds-0003-ar-160-memorial-2-to-ontario-nd-hawkridge-falconcrest', 'Memorial - 2 to Ontario nd Hawkridge - Falconcrest'),
    ('iot-rds-0003-ar-175-to-southcliff-john-st-rd-community', 'to Southcliff John St Rd - Community'),
    ('iot-rds-0003-ar-185-hall-to-lawrence-john-st-rd-lawrence-to', 'Hall to Lawrence John St Rd - Lawrence to'),
    ('iot-rds-0003-ar-197-mapleward', 'Mapleward'),
    ('iot-rds-0003-ar-203-arthur-vickers-to-brodie', 'Arthur - Vickers to Brodie'),
    ('iot-rds-0003-ar-215-southcliff-place', 'Southcliff Place'),
    ('iot-rds-0003-ar-217-beverley-st-parking-lot', 'Beverley St Parking Lot'),
    ('iot-rds-0009-li-002-local-improvements', 'Local Improvements'),
    ('iot-rds-0003-ar-045-enhanced-residential-work', 'Enhanced Residential Work'),
    ('com-flt-0007-fl-001-roads-fleet-renewal', 'Roads Fleet Renewal'),
    ('iot-rds-0004-rn-024-nw-arterial-design-nw-arterial-property', 'NW Arterial Design NW Arterial Property'),
    ('iot-eng-0001-pf-007-acquisitions', 'Acquisitions'),
    ('iot-rds-0001-br-011-program-structural-culvert', 'Program Structural Culvert'),
    ('iot-rds-0001-br-039-replacement-pacific-avenue-bridge', 'Replacement Pacific Avenue Bridge'),
    ('iot-rds-0001-br-040-reconstruction-harbour-exp-trail-girder', 'Reconstruction Harbour Exp Trail Girder'),
    ('iot-rds-0001-br-042-bridge-lyon-s-channel-oliver-rd-over-mcintyre', 'Bridge @ Lyon''s Channel Oliver Rd Over McIntyre'),
    ('iot-rds-0001-br-044-river-pedestrian-bridge-central-ave-overpass', 'River Pedestrian Bridge Central Ave Overpass'),
    ('iot-rds-0001-br-047-railing-replacement', 'Railing Replacement'),
    ('iot-rds-0001-br-049-mission-island-bridge', 'Mission Island Bridge'),
    ('iot-rds-0001-br-050-black-bay-bridge', 'Black Bay Bridge'),
    ('iot-rds-0001-br-008-inspection-william-street-bridge', 'Inspection William Street Bridge'),
    ('iot-rds-0001-br-036-design-harbour-exp-trail-bridge', 'Design Harbour Exp Trail Bridge'),
    ('iot-rds-0001-br-041-over-mcintyre-design-mckellar-island-to', 'Over McIntyre Design McKellar Island to'),
    ('iot-rds-0001-br-048-mission-island-bridge-design', 'Mission Island Bridge Design'),
    ('iot-rds-0007-ts-001-program', 'Program'),
    ('iot-rds-0007-ts-002-detection-program-audible-pedestrian', 'Detection Program Audible Pedestrian'),
    ('iot-rds-0007-ts-003-signals-signal-upgrading', 'Signals Signal Upgrading'),
    ('iot-rds-0007-ts-005-program', 'Program'),
    ('iot-rds-0007-ts-014-pedestrian-crossovers-intersection-partial', 'Pedestrian Crossovers Intersection Partial'),
    ('iot-rds-0007-ts-016-rebuilds', 'Rebuilds'),
    ('iot-rds-0007-ts-017-traffic-calming', 'Traffic Calming'),
    ('iot-rds-0007-ts-019-traffic-signal-removal-harbour-expressway', 'Traffic Signal Removal Harbour Expressway &'),
    ('iot-rds-0007-ts-039-fort-william-rd-partial-rebuild', 'Fort William Rd Partial Rebuild'),
    ('iot-rds-0010-sl-001-program-system-upgrading', 'Program System Upgrading'),
    ('iot-rds-0010-sl-002-program-pole-replacement', 'Program Pole Replacement'),
    ('iot-rds-0010-sl-004-program-underground-duct', 'Program Underground Duct'),
    ('iot-rds-0010-sl-031-replacement', 'Replacement'),
    ('iot-rds-0010-sl-032-synergy-permitting', 'Synergy Permitting'),
    ('iot-rds-0010-sl-033-fault-repairs', 'Fault Repairs'),
    ('iot-rds-0010-sl-069-brodie-miles-to-donald-victoria-archibald-to', 'Brodie - Miles to Donald Victoria - Archibald to'),
    ('iot-rds-0010-sl-070-mckellar', 'McKellar'),
    ('iot-rds-0006-sr-003-alternatives', 'Alternatives'),
    ('iot-rds-0006-sr-004-accessibility-ramp-s', 'Accessibility Ramp - S'),
    ('iot-rds-0006-sr-009-accessibility-ramp-n', 'Accessibility Ramp - N'),
    ('iot-rds-0006-sr-073-sidewalk-removals', 'Sidewalk Removals'),
    ('iot-rds-0006-sr-097-algoma-st-n-red-river-rd-to-camelot-st-w-s', 'Algoma St N - Red River Rd to Camelot St - W/S'),
    ('iot-rds-0006-sr-103-churchill-dr-w-james-st-n-to-edward-st-n-s-s', 'Churchill Dr W - James St N to Edward St N - S/S'),
    ('iot-rds-0006-sr-106-van-norman-st-jean-st-to-algoma-st-n-n-s', 'Van Norman St - Jean St to Algoma St N- N/S'),
    ('iot-rds-0008-sn-002-sidewalks-unspecified-cameron-st-bus-stop-to', 'Sidewalks (Unspecified) Cameron St - Bus Stop to'),
    ('iot-rds-0008-sn-049-vickers-st-n', 'Vickers St N'),
    ('iot-rds-0008-sn-051-oliver-rd-burwood-rd-to-golf-links', 'Oliver Rd - Burwood Rd to Golf Links'),
    ('iot-rds-0008-sn-052-sibley-dr-keewatin-st-to-balmoral-st', 'Sibley Dr - Keewatin St to Balmoral St'),
    ('iot-rds-0008-sn-056-matthews-st-margaret-st-to-clayte-st', 'Matthews St - Margaret St to Clayte St'),
    ('iot-rds-0010-sl-077-street-lighting-replacement', 'Street Lighting Replacement'),
    ('iot-rds-0006-sr-086-sidewalk-replacement', 'Sidewalk Replacement'),
    ('iot-rds-0010-sl-083-street-lighting-replacement', 'Street Lighting Replacement'),
    ('iot-rds-0006-sr-107-sidewalk-replacement', 'Sidewalk Replacement'),
    ('iot-rds-0010-sl-079-street-lighting-replacement', 'Street Lighting Replacement'),
    ('iot-rds-0006-sr-102-sidewalk-replacement', 'Sidewalk Replacement'),
    ('iot-rds-0010-sl-084-street-lighting-replacement', 'Street Lighting Replacement'),
    ('iot-rds-0006-sr-090-sidewalk-replacement', 'Sidewalk Replacement'),
    ('iot-rds-0003-ar-003-guide-rails-retaining-walls', 'Guide Rails/Retaining Walls'),
    ('iot-eng-0001-pf-001-reports-engineering-traffic', 'Reports Engineering Traffic'),
    ('iot-eng-0001-pf-002-studies', 'Studies'),
    ('iot-eng-0001-pf-004-pre-engineering-services', 'Pre-Engineering Services'),
    ('iot-eng-0001-pf-005-active-transportation-environmental', 'Active Transportation Environmental'),
    ('iot-eng-0001-pf-017-assessments', 'Assessments'),
    ('iot-eng-0001-pf-018-public-education', 'Public Education'),
    ('iot-eng-0001-pf-026-stormwater-cli-eca-asphalt-pavement', 'Stormwater CLI ECA Asphalt - Pavement'),
    ('iot-rds-0003-ar-007-management-asphalt-enhanced', 'Management Asphalt - Enhanced'),
    ('iot-rds-0003-ar-044-pavement-management', 'Pavement Management'),
    ('iot-env-0001-st-078-excess-soil-regulatory', 'Excess Soil Regulatory'),
    ('ior-san-0004-sa-065-requirement', 'Requirement'),
    ('ior-waw-0004-wr-127-ior-waw-0004-wr-127', 'IOR-WAW-0004-WR-127'),
    ('ior-waw-0001-tp-002-wtp-electrical-wtp-buildings-and', 'WTP Electrical WTP Buildings and'),
    ('ior-waw-0001-tp-005-grounds-pump-station-reservoir', 'Grounds Pump Station / Reservoir'),
    ('ior-waw-0001-tp-007-electrical-pump-station-reservoir', 'Electrical Pump Station / Reservoir'),
    ('ior-waw-0001-tp-010-buildings-and-grounds', 'Buildings and Grounds'),
    ('ior-waw-0001-tp-011-wtp-professional-fees', 'WTP Professional Fees'),
    ('ior-waw-0001-tp-012-wtp-unplanned-repairs', 'WTP Unplanned Repairs'),
    ('ior-waw-0004-wr-001-cathodic-protection', 'Cathodic Protection'),
    ('ior-waw-0004-wr-002-unspecified-replacement-s-watermain-replacement', 'Unspecified Replacement s Watermain Replacement'),
    ('ior-waw-0004-wr-014-phase-iv-sheep-ranch', 'Watermain Replacement Phase IV Sheep Ranch'),
    ('ior-waw-0004-wr-038-valves-and-chambers', 'Valves and Chambers'),
    ('ior-waw-0004-wr-056-utility-cut-restoration', 'Utility Cut Restoration'),
    ('ior-waw-0004-wr-067-sheep-ranch-rail-crossing-watermain-replacement', 'Sheep Ranch Rail Crossing Watermain Replacement'),
    ('ior-waw-0004-wr-124-phillips-phillips-to-mcauliff-watermain-replacement', 'Phillips - Phillips to McAuliff Watermain Replacement'),
    ('ior-waw-0004-wr-154-ambrose-street-watermain-replacement', 'Ambrose Street Watermain Replacement'),
    ('ior-waw-0004-wr-155-lincoln-street-watermain-replacement', 'Lincoln Street Watermain Replacement'),
    ('ior-waw-0004-wr-156-manitou-street', 'Manitou Street'),
    ('ior-waw-0004-wr-003-kerr-hydrant-replacement-lead-service', 'Kerr Hydrant Replacement Lead Service'),
    ('ior-waw-0004-wr-013-replacement-program-looping-program-quality', 'Replacement Program Looping Program - Quality'),
    ('ior-waw-0004-wr-004-and-flow-cleaning-and-cement', 'and Flow Cleaning and Cement'),
    ('ior-waw-0004-wr-017-mortar-lining-looping-waterford', 'Mortar Lining Looping - Waterford'),
    ('ior-waw-0004-wr-161-to-carrick', 'to Carrick'),
    ('ior-waw-0004-wr-163-looping-dalton-to-ray', 'Looping - Dalton to Ray'),
    ('ior-waw-0003-fw-001-equipment-replacement', 'Equipment Replacement'),
    ('ior-waw-0001-tp-001-wtp-process', 'WTP Process'),
    ('ior-waw-0001-tp-004-wtp-instrumentation-pump-station-reservoir', 'WTP Instrumentation Pump Station / Reservoir'),
    ('ior-waw-0001-tp-006-process-pump-station-reservoir', 'Process Pump Station / Reservoir'),
    ('ior-waw-0001-tp-009-instrumentation', 'Instrumentation'),
    ('ior-waw-0002-ni-001-equipment-water-use-innovation', 'Equipment Water Use Innovation'),
    ('ior-waw-0002-ni-002-program-efficiency-large-water-meter', 'Program Efficiency Large Water Meter'),
    ('ior-waw-0002-ni-004-replacement-program', 'Replacement Program'),
    ('ior-waw-0002-ni-006-water-fill-stations', 'Water Fill Stations'),
    ('ior-waw-0002-ni-011-lead-reduction-program', 'Lead Reduction Program'),
    ('ior-san-0002-ni-009-infrastructure-advanced-metering', 'Infrastructure Advanced Metering'),
    ('ior-waw-0002-ni-0014-infrastructure', 'Infrastructure'),
    ('ior-waw-0006-pw-001-studies-dwqms-audit-pre-engineering-design', 'Studies, DWQMS, Audit Pre-Engineering Design'),
    ('ior-waw-0006-pw-002-and-contract-administration', 'and Contract Administration'),
    ('ior-waw-0006-pw-006-water-model-updates', 'Water Model Updates'),
    ('ior-san-0005-wp-002-wpcp-electrical-wpcp-building-and', 'WPCP Electrical WPCP Building and'),
    ('ior-san-0005-wp-003-grounds', 'Grounds'),
    ('ior-san-0005-wp-005-wpcp-hvac-sewage-pumping', 'WPCP HVAC Sewage Pumping'),
    ('ior-san-0005-wp-006-stations', 'Stations'),
    ('ior-san-0005-wp-007-wpcp-professional-fees-wpcp-unplanned', 'WPCP Professional Fees WPCP Unplanned'),
    ('ior-san-0005-wp-008-repairs-wpcp-generator', 'Repairs WPCP Generator'),
    ('ior-san-0005-wp-009-standby-power', 'Standby Power'),
    ('ior-san-0004-sa-003-unspecified-maintenance-hole', 'Unspecified Maintenance Hole'),
    ('ior-san-0004-sa-005-appurtenance-rehabilitation-sanitary-sewer-replacement', 'Appurtenance Rehabilitation Sanitary Sewer Replacement'),
    ('ior-san-0004-sa-018-memorial-ave-queen-to-inchiquin', 'Memorial Ave - Queen to Inchiquin'),
    ('ior-san-0004-sa-004-sanitary-sewer-lining', 'Sanitary Sewer Lining'),
    ('ior-san-0004-sa-006-house-lateral-lining-sanitary-sewer-cleaning', 'House Lateral Lining Sanitary Sewer Cleaning'),
    ('ior-san-0004-sa-045-and-inspection', 'and Inspection'),
    ('ior-san-0003-fr-002-equipment-replacement-1-046-0-1-046-0', 'Equipment Replacement 1,046.0 1,046.0'),
    ('ior-san-0005-wp-001-wpcp-process', 'WPCP Process'),
    ('ior-san-0005-wp-004-wpcp-instrumentation', 'WPCP Instrumentation'),
    ('ior-san-0002-ni-001-technology', 'Technology'),
    ('ior-san-0002-ni-002-small-equipment-wastewater-innovations', 'Small Equipment Wastewater Innovations'),
    ('ior-san-0002-ni-003-program-efficiency', 'Program Efficiency'),
    ('ior-san-0007-ps-001-and-contract-admin-professional-fees-for', 'and Contract Admin Professional Fees for'),
    ('ior-san-0007-ps-002-studies', 'Studies'),
    ('ior-san-0007-ps-005-cli-eca-implementation', 'CLI-ECA Implementation'),
    ('iot-env-0001-st-001-trunk-ditching-rural-roads-rehabilitation-replacement', 'Trunk Ditching Rural Roads Rehabilitation/Replacement'),
    ('iot-env-0001-st-002-unspecified', 'Unspecified'),
    ('iot-env-0001-st-003-storm-sewer-inspections-residential-drainage', 'Storm Sewer Inspections Residential Drainage'),
    ('iot-env-0001-st-017-assistance-program', 'Assistance Program'),
    ('iot-env-0001-st-019-outfall-repairs', 'Outfall Repairs'),
    ('iot-env-0001-st-022-intercity-priorities-low-impact-development', 'Intercity Priorities Low Impact Development'),
    ('iot-env-0001-st-039-facilities-rural-drainage', 'Facilities Rural Drainage'),
    ('iot-env-0001-st-091-improvement-urban-drainage', 'Improvement Urban Drainage'),
    ('iot-env-0001-st-092-improvements', 'Improvements'),
    ('iot-sow-0003-sw-009-facility-mapleward-solid', 'Facility Mapleward Solid'),
    ('iot-cfc-0005-cs-001-waste-facility', 'Waste Facility'),
    ('iot-sow-0003-sw-007-packer-solid-waste-and', 'Packer Solid Waste and'),
    ('com-flt-0007-fl-001-diversion-fleet-renewal', 'Diversion Fleet Renewal'),
    ('iot-sow-0003-sw-001-strategy-initiatives', 'Strategy Initiatives'),
    ('iot-sow-0003-sw-002-organics-program', 'Organics Program'),
    ('iot-sow-0003-sw-004-auto-cart-program', 'Auto-Cart Program'),
    ('iot-sow-0003-sw-008-litter-receptacles', 'Litter Receptacles'),
    ('ior-sow-0001-ls-001-process-improvements-infrastructure', 'Process Improvements Infrastructure'),
    ('ior-sow-0001-ls-002-improvements', 'Improvements'),
    ('ior-sow-0001-ls-015-facility-upgrades', 'Facility Upgrades'),
    ('ior-sow-0001-ls-004-east-cell-expansion-phase-ii', 'East Cell Expansion Phase II'),
    ('ior-sow-0001-ls-008-gas-system-renewal', 'Gas System Renewal'),
    ('ior-sow-0001-ls-017-west-cell-capping-phase-ii', 'West Cell Capping Phase II'),
    ('ior-sow-0001-ls-018-west-cell-capping-phase-iii', 'West Cell Capping Phase III'),
    ('ior-sow-0002-lf-002-solid-waste-fleet-replacement', 'Solid Waste Fleet Replacement'),
    ('ior-sow-0001-ls-019-monitoring-study', 'Monitoring Study'),
    ('iot-cfc-0001-cs-010-fire-hall-facilities', 'Fire Hall Facilities'),
    ('iot-fir-0041-fr-002-pumper-rescue', 'Pumper/Rescue'),
    ('iot-fir-0041-fr-003-aerial-ladder', 'Aerial Ladder'),
    ('iot-fir-0040-fr-001-equipment-fire-hose-nozzles-and', 'Equipment Fire Hose, Nozzles and'),
    ('iot-fir-0040-fr-002-appliances-aoda-station', 'Appliances AODA Station'),
    ('iot-fir-0040-fr-005-improvements', 'Improvements'),
    ('iot-fir-0040-fr-009-auto-extrication', 'Auto Extrication'),
    ('iot-fir-0040-fr-010-pump-testing-system', 'Pump Testing System'),
    ('osb-pol-0065-ps-building-upgrades', 'Building Upgrades'),
    ('osb-pol-0036-ps-replacement', 'Replacement'),
    ('osb-pol-0001-ps-emergency-task-unit', 'Emergency Task Unit'),
    ('osb-pol-0026-ps-armoury', 'Armoury'),
    ('osb-pol-0027-ps-soft-body-armour', 'Soft Body Armour'),
    ('osb-pol-0030-ps-furniture-replacement', 'Furniture Replacement'),
    ('osb-pol-0031-ps-investigative-equipment', 'Investigative Equipment'),
    ('osb-pol-0038-ps-in-car-body-worn-cameras', 'In Car & Body Worn Cameras'),
    ('osb-pol-0045-ps-training-and-ammunition', 'Training and Ammunition'),
    ('osb-pol-0047-ps-forensics-equipment', 'Forensics Equipment'),
    ('osb-pol-0048-ps-cyber-crime-equipment', 'Cyber Crime Equipment'),
    ('osb-pol-0051-ps-uniform-patrol-equipment', 'Uniform Patrol Equipment'),
    ('osb-pol-0053-ps-traffic-management', 'Traffic Management'),
    ('osb-pol-0061-ps-other-police-equipment', 'Other Police Equipment'),
    ('osb-pol-0064-ps-cspa-equipment', 'CSPA Equipment'),
    ('osb-pol-0035-ps-maintenance', 'Maintenance'),
    ('iot-pks-0001-gp-001-lighting-and-electrical', 'Lighting and Electrical'),
    ('iot-pks-0001-gp-002-parks-upgrades-and-maintenance', 'Parks Upgrades and Maintenance'),
    ('iot-pks-0001-gp-004-amusement-rides', 'Amusement Rides'),
    ('iot-pks-0001-gp-010-playground-equipment-and-structures', 'Playground Equipment and Structures'),
    ('iot-pks-0001-gp-014-emergent-infrastructure-renewal', 'Emergent Infrastructure Renewal'),
    ('iot-pks-0001-gp-020-historical-artifact-maintenance', 'Historical Artifact Maintenance'),
    ('iot-pks-0001-gp-028-festival-area-renewal', 'Festival Area Renewal'),
    ('iot-pks-0001-gp-029-waverley-park-renewal-recreation-trail', 'Waverley Park Renewal Recreation Trail'),
    ('iot-pks-0003-rt-001-reconstruction-festival-area-renewal', 'Reconstruction Festival Area Renewal'),
    ('iot-pks-0003-rt-007-trails-public-art-maintenance', 'Trails Public Art Maintenance'),
    ('com-rec-0034-ei-008-and-minor-projects', 'and Minor Projects'),
    ('iot-pks-0002-as-002-baseball-diamonds-tennis-and-pickleball', 'Baseball Diamonds Tennis and Pickleball'),
    ('iot-pks-0002-as-003-courts-soccer-and-cricket', 'Courts Soccer and Cricket'),
    ('iot-pks-0002-as-004-fields-bleacher-seat-and-bench', 'Fields Bleacher Seat and Bench'),
    ('iot-pks-0002-as-005-replacement', 'Replacement'),
    ('iot-pks-0006-go-001-golf-course-equipment-golf-course-grounds', 'Golf Course Equipment Golf Course Grounds'),
    ('iot-pks-0006-go-002-rehabilitation-program', 'Rehabilitation Program'),
    ('ior-pal-0001-wf-001-capital-maintenance', 'Capital Maintenance'),
    ('iot-pks-0001-gp-030-urban-canopy-projects-urban-forest', 'Urban Canopy Projects Urban Forest'),
    ('iot-pks-0005-uf-001-stewardship', 'Stewardship'),
    ('iot-pks-0005-uf-002-tree-planting-program', 'Tree Planting Program'),
    ('iot-pks-0005-uf-004-eab-response', 'EAB Response'),
    ('iot-cfc-0001-cs-011-parks-facilities', 'Parks Facilities'),
    ('iot-pks-0004-me-001-small-equipment', 'Small Equipment'),
    ('com-flt-0007-fl-001-parks-fleet-renewal', 'Parks Fleet Renewal'),
    ('iot-cfc-0001-cs-006-arena-and-stadia-facilities', 'Arena and Stadia Facilities'),
    ('iot-cfc-0001-cs-007-aquatics-facilities', 'Aquatics Facilities'),
    ('iot-cfc-0001-cs-012-canada-games-complex-canada-games-complex', 'Canada Games Complex Canada Games Complex /'),
    ('com-fac-0004-fa-006-aquatics-capital-program', 'Aquatics Capital Program'),
    ('com-fac-0004-fa-007-arenas-capital-program-outdoor-pool', 'Arenas Capital Program Outdoor Pool'),
    ('iot-cfc-0001-cs-022-rehabilitation', 'Rehabilitation'),
    ('com-flt-0007-fl-002-ice-resurfacer', 'Ice Resurfacer'),
    ('com-rec-0034-ei-002-renewal', 'Renewal'),
    ('com-rec-0034-ei-018-stage-equipment-arena-and-stadia', 'Stage Equipment Arena and Stadia'),
    ('com-rec-0034-ei-020-equipment-renewal', 'Equipment Renewal'),
    ('com-rec-0032-dd-007-plan', 'Plan'),
    ('iot-cfc-0001-cs-005-tourism-facilities', 'Tourism Facilities'),
    ('iot-cfc-0001-cs-008-community-centre-facilities', 'Community Centre Facilities'),
    ('iot-cfc-0001-cs-020-older-adult-centre', 'Older Adult Centre'),
    ('com-rec-0034-ei-004-equipment', 'Equipment'),
    ('osb-lib-0010-lb-and-repair-waverley-library-elevator', 'and Repair Waverley Library Elevator'),
    ('osb-lib-0008-lb-renewal', 'Renewal'),
    ('osb-lib-0011-lb-infrastructure', 'Infrastructure'),
    ('osb-lib-0012-lb-maintenance', 'Maintenance'),
    ('osb-pkg-0001-pk-parking-meters-waterfront-district', 'Parking Meters Waterfront District'),
    ('osb-pkg-0002-pk-parkade-repairs', 'Parkade Repairs'),
    ('osb-pkg-0003-pk-victoria-parkade-repairs', 'Victoria Parkade Repairs'),
    ('iot-cfc-0001-cs-014-transit-facility', 'Transit Facility'),
    ('iot-cfc-0028-cs-002-facility-modifications', 'Facility Modifications'),
    ('com-trn-0002-ct-001-shelter-replacement-accessible-stop', 'Shelter Replacement Accessible Stop'),
    ('com-trn-0002-ct-002-improvements', 'Improvements'),
    ('com-trn-0009-ct-003-bus-wash', 'Bus Wash'),
    ('com-trn-0009-ct-006-terminal-realignment-design', 'Terminal Realignment Design'),
    ('com-flt-0007-fl-007-replacement', 'Transit Fleet Replacement'),
    ('com-trn-0009-ct-001-transit-rebranding-transit-on-demand', 'Transit Rebranding Transit On-Demand'),
    ('com-trn-0009-ct-004-vehicles', 'Vehicles'),
    ('com-trn-0002-ct-007-fleet-sign-retrofit', 'Fleet Sign Retrofit'),
    ('com-hom-0022-pj-001-reconfiguration-facility-cyclical', 'Reconfiguration Facility Cyclical'),
    ('com-hom-0022-pj-003-replacements-building-condition', 'Replacements Building Condition'),
    ('com-hom-0022-pj-009-assessment-recommendations', 'Assessment Recommendations'),
    ('com-hom-0022-pj-007-food-delivery-vehicle', 'Food Delivery Vehicle'),
    ('com-hom-0022-pj-002-replacements-jasper-furnishings-and', 'Replacements Jasper Furnishings and'),
    ('com-hom-0022-pj-004-equipment-food-services-cyclical', 'Equipment Food Services Cyclical'),
    ('com-hom-0022-pj-007-replacements-residential-furnishings', 'Replacements Residential Furnishings'),
    ('com-hom-0022-pj-008-and-equipment', 'and Equipment'),
    ('com-chc-0008-ch-002-ogden-playground-renewal', 'Ogden Playground Renewal'),
    ('com-chc-0008-ch-002-woodcrest', 'Woodcrest'),
    ('gro-dev-0002-pl-001-housing-initiatives-haf', 'Housing Initiatives (HAF)'),
    ('gro-dev-0002-pl-002-housing-initiatives-bff', 'Housing Initiatives (BFF)'),
    ('com-ems-0008-em-superior-north-ems-hq-expansion', 'Superior North EMS HQ Expansion'),
    ('cor-ems-0002-em-ambulance-replacement', 'Ambulance Replacement'),
    ('cor-ems-0001-em-medical-equipment', 'Medical Equipment'),
    ('iot-cfc-001-cs-001-corporate-facilities', 'Corporate Facilities'),
    ('iot-cfc-0001-cs-002-operational-facilities', 'Operational Facilities'),
    ('iot-cfc-0003-cs-001-whalen-building-customer-service-office', 'Whalen Building Customer Service Office'),
    ('cmo-cus-0001-cu-space-development-unplanned-major', 'Space Development Unplanned Major'),
    ('com-fac-0004-fa-002-component-repair-office-renovations', 'Component Repair Office Renovations'),
    ('gro-com-0001-cc-001-communications-asset-maintenance-and', 'Communications Asset Maintenance and'),
    ('gro-gmo-0001-ad-replacement', 'Replacement'),
    ('cor-cit-0010-it-network-software-infrastructure', 'Network & Software Infrastructure'),
    ('cor-oct-0004-sm-printing-graphics', 'Printing & Graphics'),
    ('com-fac-0004-fa-003-energy-efficiency', 'Energy Efficiency'),
    ('com-fac-0004-fa-005-security-equipment', 'Security Equipment'),
    ('iot-cfc-0018-cs-003-lighting-upgrades', 'Lighting Upgrades'),
    ('iot-cen-0002-cs-001-eye-on-the-street', 'Eye on the Street'),
    ('com-fac-0004-fa-001-diagrams-net-zero-integration', 'Diagrams Net-Zero Integration'),
    ('iot-cfc-0018-cs-001-audits-environmental', 'Audits Environmental'),
    ('com-fac-0004-fa-004-assessments', 'Assessments'),
    ('cor-cit-0009-it-digital-strategy', 'Digital Strategy'),
    ('cor-cit-0012-it-payroll-upgrade', 'Payroll Upgrade'),
    ('cmo-cus-0002-cu-customer-service-crm-implementation', 'Customer Service CRM Implementation'),
    ('cmo-hrs-0010-hr-hr-digitization', 'HR Digitization'),
    ('gro-css-0001-cc-002-city-website-renewal', 'City Website Renewal'),
    ('cmo-clk-0003-cl-aoda-compliance', 'AODA Compliance'),
    ('gen-cgb-0001-ir-beautification-and-civic-pride-initiatives', 'Beautification and Civic Pride Initiatives'),
    ('gro-gmo-0002-gm-growth-project-initiatives', 'Growth Project Initiatives'),
    ('gro-css-0002-st-002-strategic-initiatives', 'Strategic Initiatives'),
    ('gro-dev-0001-pl-001-aerial-photography', 'Aerial Photography'),
    ('gro-dev-0001-pl-002-northern-ontario-orthophotography', 'Northern Ontario Orthophotography'),
    ('gro-dev-0001-pl-003-planning-studies', 'Planning Studies')
)
UPDATE public.capital_projects p
SET name = n.name,
    official_name = n.name
FROM official_project_names n
WHERE p.id = n.id;
