WITH official_project_names(id, name) AS (
  VALUES
    ('cmo-cus-0001-cu-space-development-unplanned-major', 'Customer Service Office Space Development'),
    ('com-chc-0008-ch-002-ogden-playground-renewal', 'Playground Renewal - Ogden'),
    ('com-chc-0008-ch-002-woodcrest', 'Playground Renewal - Woodcrest'),
    ('com-fac-0004-fa-001-diagrams-net-zero-integration', 'Arc Flash / Single Line Diagrams'),
    ('com-fac-0004-fa-002-component-repair-office-renovations', 'Unplanned Major Component Repair'),
    ('com-fac-0004-fa-004-assessments', 'Environmental Assessments'),
    ('com-fac-0004-fa-006-aquatics-capital-program', 'Canada Games Complex / Aquatics Capital Program'),
    ('com-fac-0004-fa-007-arenas-capital-program-outdoor-pool', 'Arenas Capital Program'),
    ('com-flt-0007-fl-001-diversion-fleet-renewal', 'Solid Waste and Diversion Fleet Renewal'),
    ('com-hom-0022-pj-001-reconfiguration-facility-cyclical', 'Business Office Reconfiguration'),
    ('com-hom-0022-pj-002-replacements-jasper-furnishings-and', 'Equipment Cyclical Replacements'),
    ('com-hom-0022-pj-003-replacements-building-condition', 'Facility Cyclical Replacements Building Condition'),
    ('com-hom-0022-pj-004-equipment-food-services-cyclical', 'Jasper Furnishings and Equipment'),
    ('com-hom-0022-pj-007-replacements-residential-furnishings', 'Food Services Cyclical Replacements'),
    ('com-hom-0022-pj-008-and-equipment', 'Residential Furnishings and Equipment'),
    ('com-rec-0032-dd-007-plan', 'Parks & Facilities Master Plan'),
    ('com-rec-0034-ei-002-renewal', 'Aquatics and Wellness Renewal'),
    ('com-rec-0034-ei-004-equipment', 'Community Centre Equipment'),
    ('com-rec-0034-ei-008-and-minor-projects', 'Public Art Maintenance and Minor Projects'),
    ('com-rec-0034-ei-018-stage-equipment-arena-and-stadia', 'Stage Equipment'),
    ('com-rec-0034-ei-020-equipment-renewal', 'Arena and Stadia Equipment Renewal'),
    ('com-trn-0002-ct-001-shelter-replacement-accessible-stop', 'Shelter Replacement'),
    ('com-trn-0002-ct-002-improvements', 'Accessible Stop Improvements'),
    ('com-trn-0009-ct-001-transit-rebranding-transit-on-demand', 'Transit Rebranding'),
    ('com-trn-0009-ct-004-vehicles', 'Transit On-Demand Vehicles'),
    ('gro-com-0001-cc-001-communications-asset-maintenance-and', 'Office Renovations - Communications'),
    ('gro-gmo-0001-ad-replacement', 'Asset Maintenance and Replacement'),
    ('ior-san-0002-ni-001-technology', 'Plant and Program Technology'),
    ('ior-san-0002-ni-002-small-equipment-wastewater-innovations', 'Small Equipment'),
    ('ior-san-0002-ni-003-program-efficiency', 'Wastewater Innovations Program Efficiency'),
    ('ior-san-0002-ni-009-infrastructure-advanced-metering', 'Advanced Metering Infrastructure'),
    ('ior-san-0003-fr-002-equipment-replacement-1-046-0-1-046-0', 'Wastewater Fleet and Equipment Replacement'),
    ('ior-san-0004-sa-003-unspecified-maintenance-hole', 'Sanitary Sewer Unspecified Maintenance Hole'),
    ('ior-san-0004-sa-005-appurtenance-rehabilitation-sanitary-sewer-replacement', 'Appurtenance Rehabilitation Sanitary Sewer'),
    ('ior-san-0004-sa-006-house-lateral-lining-sanitary-sewer-cleaning', 'House Lateral Lining'),
    ('ior-san-0004-sa-018-memorial-ave-queen-to-inchiquin', 'Replacement Memorial Ave - Queen to Inchiquin'),
    ('ior-san-0004-sa-019-replacement', 'Sanitary Sewer Replacement'),
    ('ior-san-0004-sa-020-replacement', 'Sanitary Sewer Replacement'),
    ('ior-san-0004-sa-045-and-inspection', 'Sanitary Sewer Cleaning and Inspection'),
    ('ior-san-0004-sa-065-requirement', 'Excess Soil Regulatory Requirement'),
    ('ior-san-0004-sa-076-replacement', 'Sanitary Sewer Replacement'),
    ('ior-san-0004-sa-086-replacement', 'Sanitary Sewer Replacement'),
    ('ior-san-0004-sa-089-replacement', 'Sanitary Sewer Replacement'),
    ('ior-san-0004-sa-090-replacement', 'Sanitary Sewer Replacement'),
    ('ior-san-0004-sa-091-replacement', 'Sanitary Sewer Replacement'),
    ('ior-san-0005-wp-002-wpcp-electrical-wpcp-building-and', 'WPCP Electrical'),
    ('ior-san-0005-wp-003-grounds', 'WPCP Building and Grounds'),
    ('ior-san-0005-wp-005-wpcp-hvac-sewage-pumping', 'WPCP HVAC'),
    ('ior-san-0005-wp-006-stations', 'Sewage Pumping Stations'),
    ('ior-san-0005-wp-007-wpcp-professional-fees-wpcp-unplanned', 'WPCP Professional Fees'),
    ('ior-san-0005-wp-008-repairs-wpcp-generator', 'WPCP Unplanned Repairs'),
    ('ior-san-0005-wp-009-standby-power', 'WPCP Generator Standby Power'),
    ('ior-san-0007-ps-001-and-contract-admin-professional-fees-for', 'Pre-Engineering Design and Contract Admin'),
    ('ior-san-0007-ps-002-studies', 'Professional Fees for Studies'),
    ('ior-sow-0001-ls-001-process-improvements-infrastructure', 'Process Improvements'),
    ('ior-sow-0001-ls-002-improvements', 'Infrastructure Improvements'),
    ('ior-sow-0001-ls-019-monitoring-study', 'Environmental Monitoring Study'),
    ('ior-waw-0001-tp-002-wtp-electrical-wtp-buildings-and', 'WTP Electrical'),
    ('ior-waw-0001-tp-004-wtp-instrumentation-pump-station-reservoir', 'WTP Instrumentation'),
    ('ior-waw-0001-tp-005-grounds-pump-station-reservoir', 'WTP Buildings and Grounds'),
    ('ior-waw-0001-tp-006-process-pump-station-reservoir', 'Pump Station / Reservoir Process'),
    ('ior-waw-0001-tp-007-electrical-pump-station-reservoir', 'Pump Station / Reservoir Electrical'),
    ('ior-waw-0001-tp-009-instrumentation', 'Pump Station / Reservoir Instrumentation'),
    ('ior-waw-0001-tp-010-buildings-and-grounds', 'Pump Station / Reservoir Buildings and Grounds'),
    ('ior-waw-0002-ni-001-equipment-water-use-innovation', 'Program Technology and Equipment'),
    ('ior-waw-0002-ni-0014-infrastructure', 'Advanced Metering Infrastructure'),
    ('ior-waw-0002-ni-002-program-efficiency-large-water-meter', 'Water Use Innovation Program Efficiency'),
    ('ior-waw-0002-ni-004-replacement-program', 'Large Water Meter Replacement Program'),
    ('ior-waw-0003-fw-001-equipment-replacement', 'Waterworks Fleet and Equipment Replacement'),
    ('ior-waw-0004-wr-002-unspecified-replacement-s-watermain-replacement', 'Unspecified Replacements'),
    ('ior-waw-0004-wr-003-kerr-hydrant-replacement-lead-service', 'Kerr Hydrant Replacement'),
    ('ior-waw-0004-wr-004-and-flow-cleaning-and-cement', 'Looping Program - Quality and Flow'),
    ('ior-waw-0004-wr-013-replacement-program-looping-program-quality', 'Lead Service Replacement Program'),
    ('ior-waw-0004-wr-017-mortar-lining-looping-waterford', 'Cleaning and Cement Mortar Lining'),
    ('ior-waw-0004-wr-067-sheep-ranch-rail-crossing-watermain-replacement', 'Sheep Ranch Rail Crossing'),
    ('ior-waw-0004-wr-124-phillips-phillips-to-mcauliff-watermain-replacement', 'Watermain Replacement Phillips - Phillips to McAuliff'),
    ('ior-waw-0004-wr-154-ambrose-street-watermain-replacement', 'Watermain Replacement Ambrose Street'),
    ('ior-waw-0004-wr-155-lincoln-street-watermain-replacement', 'Watermain Replacement Lincoln Street'),
    ('ior-waw-0004-wr-156-manitou-street', 'Watermain Replacement Manitou Street'),
    ('ior-waw-0004-wr-158-expansion', 'Watermain Network Expansion'),
    ('ior-waw-0004-wr-161-to-carrick', 'Looping - Waterford to Carrick'),
    ('ior-waw-0004-wr-168-river-to-theresa', 'Watermain Replacement River to Theresa'),
    ('ior-waw-0005-ne-001-waterworks', 'Subdivision Oversizing - Waterworks'),
    ('ior-waw-0006-pw-001-studies-dwqms-audit-pre-engineering-design', 'Professional Fees for Studies, DWQMS, Audit Pre-Engineering Design'),
    ('iot-cfc-0001-cs-012-canada-games-complex-canada-games-complex', 'Canada Games Complex'),
    ('iot-cfc-0001-cs-022-rehabilitation', 'Outdoor Pool Rehabilitation'),
    ('iot-cfc-0003-cs-001-whalen-building-customer-service-office', 'Whalen Building'),
    ('iot-cfc-0005-cs-001-waste-facility', 'Mapleward Solid Waste Facility'),
    ('iot-cfc-0018-cs-001-audits-environmental', 'Net-Zero Integration Audits'),
    ('iot-eng-0001-pf-001-reports-engineering-traffic', 'Property Acquisition Reports'),
    ('iot-eng-0001-pf-002-studies', 'Engineering Traffic Studies'),
    ('iot-eng-0001-pf-005-active-transportation-environmental', 'Active Transportation'),
    ('iot-eng-0001-pf-007-acquisitions', 'NW Arterial Property Acquisitions'),
    ('iot-eng-0001-pf-017-assessments', 'Environmental Assessments'),
    ('iot-eng-0001-pf-026-stormwater-cli-eca-asphalt-pavement', 'Stormwater CLI ECA'),
    ('iot-env-0001-st-001-trunk-ditching-rural-roads-rehabilitation-replacement', 'Trunk Ditching Rural Roads'),
    ('iot-env-0001-st-002-unspecified', 'Rehabilitation/Replacement'),
    ('iot-env-0001-st-003-storm-sewer-inspections-residential-drainage', 'Storm Sewer Inspections'),
    ('iot-env-0001-st-017-assistance-program', 'Residential Drainage Assistance Program'),
    ('iot-env-0001-st-022-intercity-priorities-low-impact-development', 'Intercity Priorities'),
    ('iot-env-0001-st-039-facilities-rural-drainage', 'Low Impact Development Facilities'),
    ('iot-env-0001-st-091-improvement-urban-drainage', 'Rural Drainage Improvement'),
    ('iot-env-0001-st-092-improvements', 'Urban Drainage Improvements'),
    ('iot-env-0001-st-097-management', 'Stormwater Management'),
    ('iot-env-0001-st-105-management-watermain-network', 'Stormwater Management'),
    ('iot-fir-0040-fr-001-equipment-fire-hose-nozzles-and', 'Personal Protective Equipment'),
    ('iot-fir-0040-fr-002-appliances-aoda-station', 'Fire Hose, Nozzles and Appliances'),
    ('iot-fir-0040-fr-005-improvements', 'AODA Station Improvements'),
    ('iot-pks-0001-gp-029-waverley-park-renewal-recreation-trail', 'Waverley Park Renewal'),
    ('iot-pks-0001-gp-030-urban-canopy-projects-urban-forest', 'Urban Canopy Projects'),
    ('iot-pks-0002-as-002-baseball-diamonds-tennis-and-pickleball', 'Baseball Diamonds'),
    ('iot-pks-0002-as-003-courts-soccer-and-cricket', 'Tennis and Pickleball Courts'),
    ('iot-pks-0002-as-004-fields-bleacher-seat-and-bench', 'Soccer and Cricket Fields'),
    ('iot-pks-0002-as-005-replacement', 'Bleacher Seat and Bench Replacement'),
    ('iot-pks-0003-rt-001-reconstruction-festival-area-renewal', 'Recreation Trail Reconstruction'),
    ('iot-pks-0003-rt-007-trails-public-art-maintenance', 'Festival Area Renewal Trails'),
    ('iot-pks-0005-uf-001-stewardship', 'Urban Forest Stewardship'),
    ('iot-pks-0006-go-001-golf-course-equipment-golf-course-grounds', 'Golf Course Equipment'),
    ('iot-pks-0006-go-002-rehabilitation-program', 'Golf Course Grounds Rehabilitation Program'),
    ('iot-rds-0001-br-008-inspection-william-street-bridge', 'Detailed Visual Bridge Inspection'),
    ('iot-rds-0001-br-011-program-structural-culvert', 'Culvert Replacement Program'),
    ('iot-rds-0001-br-034-culvert-headwall-watermain-replacement', 'Culvert Headwall'),
    ('iot-rds-0001-br-036-design-harbour-exp-trail-bridge', 'William Street Bridge Design'),
    ('iot-rds-0001-br-039-replacement-pacific-avenue-bridge', 'Structural Culvert Replacement'),
    ('iot-rds-0001-br-040-reconstruction-harbour-exp-trail-girder', 'Pacific Avenue Bridge Reconstruction'),
    ('iot-rds-0001-br-041-over-mcintyre-design-mckellar-island-to', 'Harbour Exp Trail Bridge Over McIntyre Design McKellar Island to'),
    ('iot-rds-0001-br-042-bridge-lyon-s-channel-oliver-rd-over-mcintyre', 'Harbour Exp Trail Girder Bridge @ Lyon''s Channel'),
    ('iot-rds-0001-br-044-river-pedestrian-bridge-central-ave-overpass', 'Oliver Rd Over McIntyre River Pedestrian Bridge'),
    ('iot-rds-0001-br-047-railing-replacement', 'Central Ave Overpass - Railing Replacement'),
    ('iot-rds-0003-ar-001-patching-railway-crossing', 'Asphalt - Miscellaneous Patching'),
    ('iot-rds-0003-ar-006-sealing-asphalt-miscellaneous', 'Surface and Crack Sealing'),
    ('iot-rds-0003-ar-007-management-asphalt-enhanced', 'Asphalt - Pavement Management'),
    ('iot-rds-0003-ar-008-improvements-rural-roads-granular', 'Railway Crossing Improvements'),
    ('iot-rds-0003-ar-044-pavement-management', 'Asphalt - Enhanced Pavement Management'),
    ('iot-rds-0003-ar-160-memorial-2-to-ontario-nd-hawkridge-falconcrest', 'Memorial - 2nd to Ontario'),
    ('iot-rds-0003-ar-175-to-southcliff-john-st-rd-community', 'Hawkridge - Falconcrest to Southcliff'),
    ('iot-rds-0003-ar-185-hall-to-lawrence-john-st-rd-lawrence-to', 'John St Rd - Community Hall to Lawrence'),
    ('iot-rds-0003-ar-189-reconstruction', 'Pavement Reconstruction'),
    ('iot-rds-0003-ar-193-reconstruction-street-lighting', 'Pavement Reconstruction'),
    ('iot-rds-0003-ar-196-river-to-crescent', 'Pavement Reconstruction River to Crescent'),
    ('iot-rds-0003-ar-197-mapleward', 'John St Rd - Lawrence to Mapleward'),
    ('iot-rds-0003-ar-218-reconstruction-street-lighting', 'Pavement Reconstruction'),
    ('iot-rds-0003-ar-220-reconstruction-stormwater', 'Pavement Reconstruction'),
    ('iot-rds-0003-ar-221-reconstruction-sanitary-sewer', 'Pavement Reconstruction'),
    ('iot-rds-0003-ar-222-reconstruction-sanitary-sewer', 'Pavement Reconstruction'),
    ('iot-rds-0003-ar-223-reconstruction-street-lighting', 'Pavement Reconstruction'),
    ('iot-rds-0003-ar-226-reconstruction-sanitary-sewer', 'Pavement Reconstruction'),
    ('iot-rds-0003-ar-228-reconstruction-sanitary-sewer', 'Pavement Reconstruction'),
    ('iot-rds-0004-rn-024-nw-arterial-design-nw-arterial-property', 'NW Arterial Design'),
    ('iot-rds-0004-rn-028-improvements', 'Road Network Improvements'),
    ('iot-rds-0004-rn-030-improvement-traffic-signals-burwood', 'Phase 3 - Road Network Improvement'),
    ('iot-rds-0005-ru-001-upgrades', 'Rural Roads Granular Upgrades'),
    ('iot-rds-0006-sr-003-alternatives', 'Sidewalk Rehabilitation Alternatives'),
    ('iot-rds-0006-sr-077-sidewalk-replacement-sanitary-sewer', 'Sidewalk Replacement'),
    ('iot-rds-0006-sr-099-sidewalk-replacement-sanitary-sewer', 'Sidewalk Replacement'),
    ('iot-rds-0007-ts-001-program', 'Controller Upgrading Program'),
    ('iot-rds-0007-ts-002-detection-program-audible-pedestrian', 'Detection Program'),
    ('iot-rds-0007-ts-003-signals-signal-upgrading', 'Audible Pedestrian Signals'),
    ('iot-rds-0007-ts-005-program', 'Signal Upgrading Program'),
    ('iot-rds-0007-ts-014-pedestrian-crossovers-intersection-partial', 'Pedestrian Crossovers'),
    ('iot-rds-0007-ts-016-rebuilds', 'Intersection Partial Rebuilds'),
    ('iot-rds-0007-ts-037-rd-oliver-rd', 'Traffic Signals - Burwood Rd @ Oliver Rd'),
    ('iot-rds-0008-sn-002-sidewalks-unspecified-cameron-st-bus-stop-to', 'Sidewalks (Unspecified)'),
    ('iot-rds-0008-sn-048-minnesota-to-mckenzie-new-sidewalk', 'New Sidewalk Minnesota to McKenzie'),
    ('iot-rds-0008-sn-049-vickers-st-n', 'Cameron St - Bus Stop to Vickers St N'),
    ('iot-rds-0008-sn-053-prince-arthur-to-minnesota', 'New Sidewalk Prince Arthur to Minnesota'),
    ('iot-rds-0010-sl-001-program-system-upgrading', 'Underground Upgrade Program'),
    ('iot-rds-0010-sl-002-program-pole-replacement', 'System Upgrading Program'),
    ('iot-rds-0010-sl-004-program-underground-duct', 'Pole Replacement Program'),
    ('iot-rds-0010-sl-031-replacement', 'Underground Duct Replacement'),
    ('iot-rds-0010-sl-069-brodie-miles-to-donald-victoria-archibald-to', 'Brodie - Miles to Donald'),
    ('iot-rds-0010-sl-070-mckellar', 'Victoria - Archibald to McKellar'),
    ('iot-rds-0010-sl-072-replacement', 'Street Lighting Replacement'),
    ('iot-rds-0010-sl-085-replacement-sanitary-sewer', 'Street Lighting Replacement'),
    ('iot-rds-0010-sl-087-replacement', 'Street Lighting Replacement'),
    ('iot-sow-0003-sw-001-strategy-initiatives', 'Solid Waste Management Strategy Initiatives'),
    ('iot-sow-0003-sw-007-packer-solid-waste-and', 'Fleet Expansion - Waste Packer'),
    ('iot-sow-0003-sw-009-facility-mapleward-solid', 'Organics Processing Facility'),
    ('osb-lib-0008-lb-renewal', 'Waverley Library Elevator Renewal'),
    ('osb-lib-0010-lb-and-repair-waverley-library-elevator', 'Building Maintenance and Repair'),
    ('osb-lib-0011-lb-infrastructure', 'Core Public Service Infrastructure'),
    ('osb-lib-0012-lb-maintenance', 'Digital Infrastructure Maintenance'),
    ('osb-pkg-0001-pk-parking-meters-waterfront-district', 'Parking Meters'),
    ('osb-pkg-0002-pk-parkade-repairs', 'Waterfront District Parkade Repairs'),
    ('osb-pol-0035-ps-maintenance', 'Computer System Maintenance'),
    ('osb-pol-0036-ps-replacement', 'Police Vehicle Replacement')
)
UPDATE public.capital_projects p
SET name = n.name,
    official_name = n.name
FROM official_project_names n
WHERE p.id = n.id;

INSERT INTO public.capital_projects (
    id, name, official_name, service, category, asset_type, action, lifecycle, status,
    description, benefits, ward, location, source_url, source_doc, source_page, source_hash, source
)
VALUES (
    'ior-waw-0004-wr-169-watermain-replacement', 'Watermain Replacement', 'Watermain Replacement', 'Roads', 'Roads', 'Roads', 'Replace', 'renewal', 'approved',
    'Capital project line item from the City''s 2026-2027 Capital Budget table for Roads.',
    'Funding source and annual budget amounts are taken from the official capital budget project table.',
    '', '', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=10325', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=10325', 32, '96ac852c7303a36d533acf32c530463b61b59c6481e7c840c53d83a2e316ad2b', 'capital-budget-2026-2027'
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    official_name = EXCLUDED.official_name,
    service = EXCLUDED.service,
    category = EXCLUDED.category,
    asset_type = EXCLUDED.asset_type,
    action = EXCLUDED.action,
    lifecycle = EXCLUDED.lifecycle,
    status = EXCLUDED.status,
    description = EXCLUDED.description,
    benefits = EXCLUDED.benefits,
    ward = EXCLUDED.ward,
    location = EXCLUDED.location,
    source_url = EXCLUDED.source_url,
    source_doc = EXCLUDED.source_doc,
    source_page = EXCLUDED.source_page,
    source_hash = EXCLUDED.source_hash,
    source = EXCLUDED.source;

INSERT INTO public.capital_project_years (project_id, fiscal_year, amount, budget_status, source_url, source_doc, source_page, source)
VALUES ('ior-waw-0004-wr-169-watermain-replacement', 2026, 1500000.00, 'approved', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=10325', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=10325', 32, 'capital-budget-2026-2027')
ON CONFLICT (project_id, fiscal_year) DO UPDATE
SET amount = EXCLUDED.amount,
    budget_status = EXCLUDED.budget_status,
    source_url = EXCLUDED.source_url,
    source_doc = EXCLUDED.source_doc,
    source_page = EXCLUDED.source_page,
    source = EXCLUDED.source;

INSERT INTO public.capital_project_funding (project_id, fiscal_year, funding_source, funding_kind, amount, source_url, source_doc, source_page, source)
VALUES ('ior-waw-0004-wr-169-watermain-replacement', 2026, 'Debenture (Rate Supported: Waterworks)', 'debenture', 1500000.00, 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=10325', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=10325', 32, 'capital-budget-2026-2027')
ON CONFLICT (project_id, fiscal_year, funding_source) DO UPDATE
SET funding_kind = EXCLUDED.funding_kind,
    amount = EXCLUDED.amount,
    source_url = EXCLUDED.source_url,
    source_doc = EXCLUDED.source_doc,
    source_page = EXCLUDED.source_page,
    source = EXCLUDED.source;

INSERT INTO public.capital_project_stakeholders (project_id, name, role, organization, stakeholder_type, source_url, source_doc, source_page, source)
VALUES ('ior-waw-0004-wr-169-watermain-replacement', 'Roads', 'owner', 'City of Thunder Bay', 'internal', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=10325', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=10325', 32, 'capital-budget-2026-2027')
ON CONFLICT (project_id, name, role) DO UPDATE
SET organization = EXCLUDED.organization,
    stakeholder_type = EXCLUDED.stakeholder_type,
    source_url = EXCLUDED.source_url,
    source_doc = EXCLUDED.source_doc,
    source_page = EXCLUDED.source_page,
    source = EXCLUDED.source;

INSERT INTO public.capital_project_approvals (
    approval_id, project_id, fiscal_year, approval_stage, approval_date, approval_body,
    meeting_id, motion_id, result, source_url, source_doc, source_page, source_hash, source
)
VALUES (
    'capital-budget-2026-2027-ior-waw-0004-wr-169-watermain-replacement', 'ior-waw-0004-wr-169-watermain-replacement', NULL, 'capital_budget_approval', '2025-11-24', 'Committee of the Whole - Budget',
    NULL, NULL, 'CARRIED', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=11040', 'https://pub-thunderbay.escribemeetings.com/FileStream.ashx?DocumentId=11040', 3, '48f9116eedde066b119341c3a31edfd8c1b07fa12406385c162f93d0dfc63231', 'capital-budget-2026-2027'
)
ON CONFLICT (approval_id) DO UPDATE
SET project_id = EXCLUDED.project_id,
    fiscal_year = EXCLUDED.fiscal_year,
    approval_stage = EXCLUDED.approval_stage,
    approval_date = EXCLUDED.approval_date,
    approval_body = EXCLUDED.approval_body,
    meeting_id = EXCLUDED.meeting_id,
    motion_id = EXCLUDED.motion_id,
    result = EXCLUDED.result,
    source_url = EXCLUDED.source_url,
    source_doc = EXCLUDED.source_doc,
    source_page = EXCLUDED.source_page,
    source_hash = EXCLUDED.source_hash,
    source = EXCLUDED.source;
