ALTER TABLE public.capital_projects
    ADD COLUMN IF NOT EXISTS source_context text DEFAULT ''::text NOT NULL;

WITH official_contexts(id, source_context) AS (
  VALUES
    ('iot-rds-0003-ar-214-pavement-resurfacing-golf-links-harbour', 'Innova Park Development'),
    ('iot-rds-0004-rn-031-expressway-lane-expansion', 'Innova Park Development'),
    ('iot-rds-0008-sn-057-sidewalks', 'Innova Park Development'),
    ('iot-rds-0007-ts-038-traffic-signals', 'Innova Park Development'),
    ('iot-env-0001-st-104-stormwater-pond', 'Innova Park Development'),
    ('iot-rds-0004-rn-028-improvements', 'Central Avenue Development Lands'),
    ('ior-san-0001-ne-009-sanitary-sewer', 'Central Avenue Development Lands'),
    ('ior-waw-0005-ne-004-watermain', 'Central Avenue Development Lands'),
    ('iot-rds-0004-rn-030-improvement-traffic-signals-burwood', 'Burwood Road Extension'),
    ('iot-rds-0007-ts-037-rd-oliver-rd', 'Burwood Road Extension'),
    ('ior-san-0001-ne-008-phase-3-sanitary-sewer', 'Burwood Road Extension'),
    ('ior-waw-0005-ne-003-phase-3-watermain', 'Burwood Road Extension'),
    ('iot-env-0001-st-105-management-watermain-network', 'Empire Avenue - Brown Street to 100 Metres West'),
    ('ior-waw-0004-wr-158-expansion', 'Empire Avenue - Brown Street to 100 Metres West'),
    ('ior-waw-0005-ne-001-waterworks', 'Subdivision Oversizing'),
    ('ior-san-0001-ne-001-subdivision-oversizing-wastewater', 'Subdivision Oversizing'),
    ('iot-rds-0003-ar-198-surface-treatment', 'Subdivision Oversizing'),
    ('iot-rds-0003-ar-189-reconstruction', 'Brock Street - Brown Street to Heath Street'),
    ('iot-rds-0010-sl-074-streetlighting', 'Brock Street - Brown Street to Heath Street'),
    ('iot-rds-0006-sr-077-sidewalk-replacement-sanitary-sewer', 'Brock Street - Brown Street to Heath Street'),
    ('ior-san-0004-sa-076-replacement', 'Brock Street - Brown Street to Heath Street'),
    ('ior-waw-0004-wr-141-watermain-replacement', 'Brock Street - Brown Street to Heath Street'),
    ('iot-rds-0003-ar-218-reconstruction-street-lighting', 'Cumberland Street - Tupper Street to Pearl Street'),
    ('iot-rds-0010-sl-085-replacement-sanitary-sewer', 'Cumberland Street - Tupper Street to Pearl Street'),
    ('ior-san-0004-sa-089-replacement', 'Cumberland Street - Tupper Street to Pearl Street'),
    ('ior-waw-0004-wr-169-watermain-replacement', 'Cumberland Street - Tupper Street to Pearl Street'),
    ('iot-rds-0003-ar-228-reconstruction-sanitary-sewer', 'College Street - Herbert Street to Red River Road'),
    ('ior-san-0004-sa-019-replacement', 'College Street - Herbert Street to Red River Road'),
    ('ior-waw-0004-wr-172-watermain-replacement', 'College Street - Herbert Street to Red River Road'),
    ('iot-rds-0003-ar-220-reconstruction-stormwater', 'Martin Avenue - Ponderosa Drive to 180 Metres East'),
    ('iot-env-0001-st-097-management', 'Martin Avenue - Ponderosa Drive to 180 Metres East'),
    ('ior-waw-0004-wr-170-watermain-looping', 'Martin Avenue - Ponderosa Drive to 180 Metres East'),
    ('iot-rds-0010-sl-078-street-lighting-duct', 'Luci Court - Isabella Street to Moodie Street'),
    ('iot-rds-0006-sr-099-sidewalk-replacement-sanitary-sewer', 'Luci Court - Isabella Street to Moodie Street'),
    ('ior-san-0004-sa-086-replacement', 'Luci Court - Isabella Street to Moodie Street'),
    ('ior-waw-0004-wr-027-watermain-replacement', 'Luci Court - Isabella Street to Moodie Street'),
    ('iot-rds-0003-ar-196-river-to-crescent', 'Madeline Street - River Street to Crescent Avenue'),
    ('iot-rds-0001-br-034-culvert-headwall-watermain-replacement', 'Madeline Street - River Street to Crescent Avenue'),
    ('ior-waw-0004-wr-168-river-to-theresa', 'Madeline Street - River Street to Crescent Avenue'),
    ('iot-rds-0008-sn-048-minnesota-to-mckenzie-new-sidewalk', 'Pacific Avenue - Prince Arthur Boulevard to McKenzie Street'),
    ('iot-rds-0008-sn-053-prince-arthur-to-minnesota', 'Pacific Avenue - Prince Arthur Boulevard to McKenzie Street'),
    ('ior-waw-0004-wr-157-watermain-replacement', 'Pacific Avenue - Prince Arthur Boulevard to McKenzie Street'),
    ('iot-rds-0003-ar-221-reconstruction-sanitary-sewer', 'McMillan Street - Southern Avenue to Pacific Avenue'),
    ('ior-san-0004-sa-090-replacement', 'McMillan Street - Southern Avenue to Pacific Avenue'),
    ('ior-waw-0004-wr-171-watermain-replacement', 'McMillan Street - Southern Avenue to Pacific Avenue'),
    ('iot-rds-0003-ar-222-reconstruction-sanitary-sewer', 'McIntyre Street - Court Street to Cumberland Street'),
    ('ior-san-0004-sa-091-replacement', 'McIntyre Street - Court Street to Cumberland Street'),
    ('ior-waw-0004-wr-174-watermain-replacement', 'McIntyre Street - Court Street to Cumberland Street'),
    ('iot-rds-0003-ar-223-reconstruction-street-lighting', 'Juniper Drive - Clarkson Street to Alder Avenue'),
    ('iot-rds-0010-sl-087-replacement', 'Juniper Drive - Clarkson Street to Alder Avenue'),
    ('ior-waw-0004-wr-135-watermain-replacement', 'Juniper Drive - Clarkson Street to Alder Avenue'),
    ('iot-rds-0003-ar-193-reconstruction-street-lighting', 'Maple Avenue - Windsor Street to Juniper Drive'),
    ('iot-rds-0010-sl-072-replacement', 'Maple Avenue - Windsor Street to Juniper Drive'),
    ('ior-waw-0004-wr-153-watermain-replacement', 'Maple Avenue - Windsor Street to Juniper Drive'),
    ('iot-rds-0003-ar-226-reconstruction-sanitary-sewer', 'Regent Street - Van Norman Street to Red River Road'),
    ('ior-san-0004-sa-020-replacement', 'Regent Street - Van Norman Street to Red River Road'),
    ('ior-waw-0004-wr-088-watermain-replacement', 'Regent Street - Van Norman Street to Red River Road'),
    ('iot-rds-0003-ar-234-county-blvd-perth-to-east', 'County Boulevard - Perth Crescent to East Avenue'),
    ('iot-rds-0003-ar-240-algonquin-ave-john-st-to-tokio-st', 'Algonquin Avenue - John Street to Tokio Street'),
    ('iot-env-0001-st-106-algonquin-ave-john-st-to-tokio-st', 'Algonquin Avenue - John Street to Tokio Street')
)
UPDATE public.capital_projects p
SET source_context = c.source_context
FROM official_contexts c
WHERE p.id = c.id;
