/**
 * Frontend-only types not generated from Go structs.
 * For API response types, see api.gen.ts (generated by go run scripts/gen-ts-types.go).
 */
import type { VehiclePayload } from "./api.gen";

// Every SSE frame carries a server-published `status`. Vehicle data is only
// present on "live" frames; "sleep" and "stale" are status-only markers.
export type StreamStatus = "live" | "sleep" | "stale";

export interface StatusFrame {
  status: StreamStatus;
}
export type SSEPayload = (VehiclePayload & StatusFrame) | StatusFrame;

// Leaflet marker discriminated union — prevents calling wrong methods.
export interface CircleStop {
  readonly kind: "circle";
  readonly marker: L.CircleMarker;
  readonly stopId: string;
  readonly stopName: string;
  readonly isHub: boolean;
  readonly isTimepoint: boolean;
  readonly hasAlert: boolean;
}

export interface LandmarkStop {
  readonly kind: "landmark";
  readonly marker: L.Marker;
  readonly stopId: string;
  readonly stopName: string;
}

export type MapStop = CircleStop | LandmarkStop;

export function setStopStyle(stop: MapStop, style: L.CircleMarkerOptions): void {
  if (stop.kind === "circle") {
    stop.marker.setStyle(style);
  }
}

export function bringStopToFront(stop: MapStop): void {
  if (stop.kind === "circle") {
    stop.marker.bringToFront();
  }
}

